# Script for R4DS -> https://r4ds.hadley.nz

# Little function to install all needed packages in a loop - generated by Copilot
# List of packages to check and install if necessary
packages <- c("tidyverse", "ggthemes", "palmerpenguins", "devtools")

# Function to check if a package is installed, and if not, install it
install_if_missing <- function(pkg) {
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg, dependencies = TRUE)
    library(pkg, character.only = TRUE)
  }
}

# Loop through the list of packages and install if missing
for (pkg in packages) {
  install_if_missing(pkg)
}

# Load Conflicted
devtools::install_github("r-lib/conflicted")
library(conflicted)

# Create plot
ggplot(data = penguins)

# Create plot with mapping
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
)

# Create plot with mapping and geom_point
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point()

# Create plot with mapping, geom_point and color
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g, color = species)
) +
  geom_point()

# Create plot with mapping, geom_point, color and geom_smooth
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g, color = species)
) +
  geom_point() +
  geom_smooth(method = "lm")

# Create plot with mapping, geom_point, color (at local level not global) and geom_smooth
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point(mapping = aes(color = species)) +
  geom_smooth(method = "lm")

# Create plot with mapping, geom_point, color and shape (at local level not global), and geom_smooth
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point(mapping = aes(color = species, shape = species)) +
  geom_smooth(method = "lm")

# Create plot with mapping, geom_point, color and shape (at local level not global), and geom_smooth, labels and colour-blind theming
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point(aes(color = species, shape = species)) +
  geom_smooth(method = "lm") +
  labs(
    title = "Body mass and flipper length",
    subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
    x = "Flipper length (mm)", y = "Body mass (g)",
    color = "Species", shape = "Species"
  ) +
  scale_color_colorblind()
ggsave(filename="penguin_plot.png")