# Script for R4DS Chapter 3 -> https://r4ds.hadley.nz

# Little function to install all needed packages in a loop - generated by Copilot
# List of packages to check and install if necessary
packages <- c("tidyverse", "nycflights13")

# Function to check if a package is installed, and if not, install it
install_if_missing <- function(pkg) {
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg, dependencies = TRUE)
    library(pkg, character.only = TRUE)
  }
}

# Loop through the list of packages and install if missing
for (pkg in packages) {
  install_if_missing(pkg)
}
