# Script for R4DS Chapter 7 -> https://r4ds.hadley.nz

# Little function to install all needed packages in a loop - generated by Copilot
# List of packages to check and install if necessary
packages <- c("tidyverse", "janitor")

# Function to check if a package is installed, and if not, install it
install_if_missing <- function(pkg) {
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg, dependencies = TRUE)
    library(pkg, character.only = TRUE)
  }
}

# Loop through the list of packages and install if missing
for (pkg in packages) {
  install_if_missing(pkg)
}

# Load data
students <- read_csv("https://pos.it/r4ds-students-csv", na = c("", "N/A"))

# Clean data
students <- students |>
  janitor::clean_names() |>
  mutate(
    meal_plan = factor(meal_plan),
    age = parse_number(if_else(age == "five", "5", age))
  )

# Read sales files
sales_files <- c(
  "https://pos.it/r4ds-01-sales",
  "https://pos.it/r4ds-02-sales",
  "https://pos.it/r4ds-03-sales"
)
read_csv(sales_files, id = "file")

# Write to file
write_csv(students, "students.csv")
students_2 <- read_csv("students.csv")

# Data Entry with Tibbles
tibble1 <- tibble(
  x = c(1, 2, 5), 
  y = c("h", "m", "g"),
  z = c(0.08, 0.83, 0.60)
)

# Data Entry by row -> Tribbles
tribble1 <- tribble(
  ~x, ~y, ~z,
  1, "h", 0.08,
  2, "m", 0.83,
  5, "g", 0.60
)