# Script for R4DS Chapter 9 -> https://r4ds.hadley.nz

# Little function to install all needed packages in a loop - generated by Copilot
# List of packages to check and install if necessary
packages <- c("tidyverse", "ggridges")

# Function to check if a package is installed, and if not, install it
install_if_missing <- function(pkg) {
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg, dependencies = TRUE)
    library(pkg, character.only = TRUE)
  }
}

# Loop through the list of packages and install if missing
for (pkg in packages) {
  install_if_missing(pkg)
}

# View data
View(mpg)

# Create a plot (color or shape)
# With each class having a diff. color
ggplot(mpg, aes(x = displ, y = hwy, color = class)) +
  geom_point()

# With each class having a diff. shape
ggplot(mpg, aes(x = displ, y = hwy, shape = class)) +
  geom_point()

# With each class having a diff. size
ggplot(mpg, aes(x = displ, y = hwy, size = class)) +
  geom_point()
# Warning: Using size for a discrete variable is not advised.

# With each class having a diff. alpha
ggplot(mpg, aes(x = displ, y = hwy, alpha = class)) +
  geom_point()
# Warning: Using alpha for a discrete variable is not advised.

# Aesthetic coloring
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point(color = "blue")

# Each class is pink filled-in triangles
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(color = "pink", shape = 17)

# Geom point vs Geom smooth
# geom_point()
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point()

# geom_smooth()
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_smooth()

# Aesthetics for geom_smooth()
# Shape (ignored because shape doesnt work for geom_smooth)
ggplot(mpg, aes(x = displ, y = hwy, shape = drv)) + 
  geom_smooth()

# Linetype
ggplot(mpg, aes(x = displ, y = hwy, linetype = drv)) + 
  geom_smooth()

# Color and then linetype (two geoms on one graph)
ggplot(mpg, aes(x = displ, y = hwy, color = drv)) + 
  geom_point() +
  geom_smooth(aes(linetype = drv))

# We can use different aesthetics for different layers
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth()

# We can use different aesthetics for different layers, and here the local argument overrides the global
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_point(
    data = mpg |> filter(class == "2seater"), 
    color = "red"
  ) +
  geom_point(
    data = mpg |> filter(class == "2seater"), 
    shape = "circle open", size = 3, color = "red"
  )

# Geoms are fundamentals of ggplot (see examples of data displayed different ways below)
# Histogram
ggplot(mpg, aes(x = hwy)) +
  geom_histogram(binwidth = 2)

# Density plot
ggplot(mpg, aes(x = hwy)) +
  geom_density()

# Boxplot
ggplot(mpg, aes(x = hwy)) +
  geom_boxplot()

# More geoms! E.g. ggridges
ggplot(mpg, aes(x = hwy, y = drv, fill = drv, color = drv)) +
  geom_density_ridges(alpha = 0.5, show.legend = FALSE)

# Faceting
# Split into subplots by a category. here - number of cylinders
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point() + 
  facet_wrap(~cyl)

# Grid of plots. here - number of cylinders by drive type
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point() + 
  facet_grid(drv ~ cyl)

# Grid of plots with free scales
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point() + 
  facet_grid(drv ~ cyl, scales = "free")

# Statistical Transformations
# E.g. geom_bar() buts stat.count() result on the y-axis
ggplot(diamonds, aes(x = cut)) + 
  geom_bar()

# You might want to override the default stat
# 1. Replace y with another variable
diamonds |>
  count(cut) |>
  ggplot(aes(x = cut, y = n)) +
  geom_bar(stat = "identity")

# 2. Change the stat to something else, e.g. proportions instead of count
ggplot(diamonds, aes(x = cut, y = after_stat(prop), group = 1)) + 
  geom_bar()

# 3. Draw attention to stat transforms in your code
ggplot(diamonds) + 
  stat_summary(
    aes(x = cut, y = depth),
    fun.min = min,
    fun.max = max,
    fun = median
  )

# Position adjustments
# Color bar chart
ggplot(mpg, aes(x = drv, color = drv)) + 
  geom_bar()

# Fill bar chart
ggplot(mpg, aes(x = drv, fill = drv)) + 
  geom_bar()

# ggplot will automatically stack the bars for certain variables
ggplot(mpg, aes(x = drv, fill = class)) + 
  geom_bar()

# If you want to dodge the bars, use position = "dodge"
# Other option is Identity (overlapping bars)
# Fill
ggplot(mpg, aes(x = drv, fill = class)) + 
  geom_bar(position = "fill")

# Dodge
ggplot(mpg, aes(x = drv, fill = class)) + 
  geom_bar(position = "dodge")

# A Problem with Scatter plots: overplotting
# Overplotting is when multiple points are plotted on top of each other
# This can be solved by using jitter to add a bit of random noise to each point
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point(position = "jitter")

# Coordinate systems in ggplot
nz <- map_data("nz")

ggplot(nz, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "white", color = "black")

# coord_quickmap() is a quick way to get a reasonable map projection - see Maps chapter of ggplot2 book for more (https://ggplot2-book.org/maps.html)
ggplot(nz, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "white", color = "black") +
  coord_quickmap()

# Polar coords
bar <- ggplot(data = diamonds) + 
  geom_bar(
    mapping = aes(x = clarity, fill = clarity), 
    show.legend = FALSE,
    width = 1
  ) + 
  theme(aspect.ratio = 1)

bar + coord_flip()
bar + coord_polar()

# A New and Improved graphing template
# ggplot(data = <DATA>) + 
# <GEOM_FUNCTION>(
#   mapping = aes(<MAPPINGS>),
#   stat = <STAT>, 
#   position = <POSITION>
# ) +
# <COORDINATE_FUNCTION> +
# <FACET_FUNCTION>